apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infocepo-mcp-external-ingress
  namespace: demo1
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: public
  tls:
    - hosts:
        - mcp.ailab.infocepo.com
      secretName: mcp-ailab-infocepo-com-tls
  rules:
    - host: mcp.ailab.infocepo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: infocepo-mcp-external
                port:
                  number: 8085
